### ISSUE TITLE
Secondary route is hard coding slug instead of pulling in content dynamically

### ISSUE THREAD

**Issue by ViolanteCodes** [ButterCMS/gridsome-starter-buttercms#4]
Video explainer: [link](https://share.getcloudapp.com/qGuZo7gW)

From checklist item:

- [ ] Secondary route is set to /landing-page/<slug>/ to enable previewing in ButterCMS.com
iframe panel, as iframe panel does not currently explicitly allow previewing of index.

**Comment by prokopsimek** [comment]
Fixed in #7
